name: dw_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  date_format: ^2.0.2
  intl: "0.19.0"
  get_it: ^7.2.0
  logger: ^1.0.0
  indexed: ^0.0.8
  styled_text: ^8.1.0
  url_launcher: ^6.2.4
  sprintf: ^7.0.0
  crypto: ^3.0.6
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  flutter_dotenv: ^5.0.2
  defer_pointer: ^0.0.2
  flutter_xlider: ^3.5.0
  hovering: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/data/
    - assets/img/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.otf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.otf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.otf
          weight: 900

